archives:
- format_overrides:
  - goos: windows
    format: zip
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: windows
    goarch: arm
  - goos: windows
    goarch: arm64
  - goos: darwin
    goarch: arm
